name: Java CI

on: [push]

jobs:
  formatting:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2 # v2 minimum required
        - uses: axel-op/googlejavaformat-action@v3
          with:
            args: "--skip-sorting-imports --replace"
            githubToken: ${{ secrets.GITHUB_TOKEN }}

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
